#!/usr/bin/env bash
# install nginx on web-01 server

apt-get update
apt-get upgrade -y
sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i 's/listen 80 default_server/listen 80/' /etc/nginx/sites-available/default
sudo service nginx restart
echo "Hello World" | sudo tee /var/www/html/index.html
curl http://localhost/
