#!/usr/bin/env bash
#This script displays numbers from 1-100 and certain multiples have different outputs
export i=0
for i in {1..100}; do
	echo "i"
	i=$((i+1))
        if (( i % 15 == 0 )); then
        echo "FizzBuzz"
fi
        if (( i % 3 == 0 )); then
        echo "Fizz"
fi                
        if (( i % 5 == 0 )); then
	echo "Buzz"
fi
done
