#!/usr/bin/env bash
#This script displays numbers from 1-100 and certain multiples have different outputs
export i=1
for i in {1..100}; do
	i=$((i++))
        if (( i % 3 == 0 )); then
        echo "Fizz"
	elif (( i % 5 == 0 )); then
        echo "Buzz"          
	elif (( i % 15 == 0 )); then
	echo "FizzBuzz"
	else
		echo "$i"
fi
done
