#!/usr/bin/env bash
#This script displays "Best School" 10 times and "Hi" once
i=1
while [ $i -le 10 ]; do
	echo "Best School"
	i=$((i+1))
if [ $i = 9 ]; then
	echo -e "Best School\nHi"
	i=$((i+1))
fi
done
