#!/usr/bin/env bash
#This script displays "Best School" 10 times and "Hi" once
i=1
while [ $i -le 10 ]; do
	echo "Best School"
	i=$((i+1))
while [ $i = 9 ]; do
	echo -e "Best School \nHi"
	i=$((i+1))
done
done
