#!/usr/bin/env bash
#Script that gives info about the school file
file=./school
if [[ -e $file ]]; then
	echo "school file exists"
else
	echo "school file does not exist"
fi
if [[ -s $file ]]; then
	echo "school file is empty"
else
	echo "school file is not empty"
fi
if [[ -f $file ]]; then
	echo "school is a regular file"
else
       "true"
fi
