#!/usr/bin/env bash
# installing load balancer

apt-get update
apt-get -y upgrade
apt-get -y install haproxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
cat <<EOT > /etc/haproxy/haproxy.cfg
defaults
    mode    http
frontend http-in
    bind    *:80
    default_backend servers
backend servers
    balance roundrobin
    server  5556-web-01 13.38.111.67:80 check
    server  5556-web-02 15.188.195.21:80 check
EOT
sudo service haproxy restart
