#!/usr/bin/env bash
#Installing and setting up ufw
apt-get install ufw
# Block all incoming traffic but
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp  #SSH    
ufw allow 80/tcp  #HTTP
ufw allow 443/tcp #HTTPS SSL
# Enable ufw
ufw enable
ufw status verbose
